import org.gradle.accessors.dm.LibrariesForLibs

plugins {
    // https://docs.gradle.org/current/userguide/custom_plugins.html
    `java-gradle-plugin`
    // https://docs.gradle.org/current/userguide/custom_plugins.html#sec:precompiled_plugins
    `kotlin-dsl`
    `kotlin-dsl-precompiled-script-plugins`

    `version-catalog`
}

//group = "io.bloco.template.buildlogic"
group = libs.versions.app.namespace.get() + ".buildlogic"

//java {
//    sourceCompatibility = JavaVersion.VERSION_11
//    targetCompatibility = JavaVersion.VERSION_11
//}

dependencies {
    compileOnly(libs.gradle.plugin.android)
    compileOnly(libs.gradle.plugin.kotlin)
    compileOnly(gradleKotlinDsl())
    compileOnly(gradleApi())
    // Accessors to autogenerated version catalog
    // Without the useless cast intelliJ has a syntax highlighting issue and will
    // incorrectly warn that libs.javaClass won't compile
    @Suppress("USELESS_CAST")
    implementation(
        files((libs as LibrariesForLibs).javaClass.superclass.protectionDomain.codeSource.location))
}

gradlePlugin {
    plugins {
//        register("coroutines") {
//            id = "template.coroutines"
//            implementationClass = "CoroutinesConventionPlugin"
//        }

        register("kotlinFeature") {
            id = "template.feature"
            implementationClass = "TemplateFeatureConventionPlugin"
        }
    }
}
